name: 'Maximize build disk space'
description: 'Maximize the available disk space for your build job'
branding:
  icon: 'crop'
  color: 'orange'
inputs:
  root-reserve-mb:
    description: 'Space to be left free on the root filesystem, in Megabytes.'
    required: false
    default: '1024'
  temp-reserve-mb:
    description: 'Space to be left free on the temp filesystem (/mnt), in Megabytes.'
    required: false
    default: '100'
  swap-size-mb:
    description: 'Zram swap space to create, in Megabytes.'
    required: false
    default: '16384'
  min-space-gb:
    description: 'Perform a free space check at the end of the action. The step will fail if not pass. in Gigabytes'
    required: false
    default: '10'
  overprovision-lvm:
    description: |
      Create the LVM disk images as sparse files, making the space required for the LVM image files *appear* unused on the
      hosting volumes until actually allocated. Use with care, this can lead to surprising out-of-disk-space situations.
      You should prefer adjusting root-reserve-mb/temp-reserve-mb over using this option.
    required: false
    default: 'false'
  btrfs:
    description: |
      Create an btrfs filesystem over loopback images and use it as a workspace.
      This can take advantage of Btrfs compression, with zstd level 3 enabled.
      NOTE this overrides all LVM options
    required: false
    default: 'false'
  build-mount-path:
    description: 'Absolute path to the mount point where the build space will be available, defaults to $GITHUB_WORKSPACE if unset.'
    required: false
  build-mount-path-ownership:
    description: 'Ownership of the mount point path, defaults to standard "runner" user and group.'
    required: false
    default: 'runner:runner'
  pv-loop-path:
    description: 'Absolute file path for the LVM image created on the root filesystem, the default is usually fine.'
    required: false
    default: '/pv.img'
  tmp-pv-loop-path:
    description: 'Absolute file path for the LVM image created on the temp filesystem, the default is usually fine. Must reside on /mnt'
    required: false
    default: '/mnt/tmp-pv.img'
  remove-dotnet:
    description: 'Removes .NET runtime and libraries. (frees ~17 GB)'
    required: false
    default: 'false'
  remove-android:
    description: 'Removes Android SDKs and Tools. (frees ~11 GB)'
    required: false
    default: 'false'
  remove-haskell:
    description: 'Removes GHC (Haskell) artifacts. (frees ~2.7 GB)'
    required: false
    default: 'false'
  remove-codeql:
    description: 'Removes CodeQL Action Bundles. (frees ~5.4 GB)'
    required: false
    default: 'false'
  remove-docker-images:
    description: 'Removes cached Docker images. (frees ~3 GB)'
    required: false
    default: 'false'
  remove-aggressive:
    description: 'Removes more preinstall toolchains and sdks (frees ~10 GB)'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Disk space report before modification
      shell: bash
      run: |
        echo "Memory and swap:"
        sudo free -h
        echo
        sudo swapon --show
        echo

        echo "Available storage:"
        sudo df -h
        echo

    - name: Maximize build disk space
      shell: bash
      run: |
          set -euo pipefail

          BUILD_MOUNT_PATH="${{ inputs.build-mount-path }}"
          if [[ -z "${BUILD_MOUNT_PATH}" ]]; then
            BUILD_MOUNT_PATH="${GITHUB_WORKSPACE}"
          fi

          echo "Arguments:"
          echo
          echo "  Root reserve:      ${{ inputs.root-reserve-mb }} MiB"
          echo "  Temp reserve:      ${{ inputs.temp-reserve-mb }} MiB"
          echo "  Swap space:        ${{ inputs.swap-size-mb }} MiB"
          echo "  Overprovision LVM: ${{ inputs.overprovision-lvm }}"
          echo "  Mount path:        ${BUILD_MOUNT_PATH}"
          echo "  Root PV loop path: ${{ inputs.pv-loop-path }}"
          echo "  Temp PV loop path: ${{ inputs.tmp-pv-loop-path }}"
          echo -n "  Removing:     "
          if [[ ${{ inputs.remove-dotnet }} == 'true' ]]; then
            echo -n "dotnet "
          fi
          if [[ ${{ inputs.remove-android }} == 'true' ]]; then
            echo -n "android "
          fi
          if [[ ${{ inputs.remove-haskell }} == 'true' ]]; then
            echo -n "haskell "
          fi
          if [[ ${{ inputs.remove-codeql }} == 'true' ]]; then
            echo -n "codeql "
          fi
          if [[ ${{ inputs.remove-docker-images }} == 'true' ]]; then
            echo -n "docker "
          fi
          echo

          # store owner of $GITHUB_WORKSPACE in case the action deletes it
          WORKSPACE_OWNER="$(stat -c '%U:%G' "${GITHUB_WORKSPACE}")"

          # ensure mount path exists before the action
          sudo mkdir -p "${BUILD_MOUNT_PATH}"
          sudo find "${BUILD_MOUNT_PATH}" -maxdepth 0 ! -empty -exec echo 'WARNING: directory [{}] is not empty, data loss might occur. Content:' \; -exec ls -al "{}" \;

          echo "Removing unwanted software... "
          if [[ ${{ inputs.remove-dotnet }} == 'true' ]]; then
            sudo rm -rf /usr/share/dotnet
          fi
          if [[ ${{ inputs.remove-android }} == 'true' ]]; then
            sudo rm -rf /usr/local/lib/android
          fi
          if [[ ${{ inputs.remove-haskell }} == 'true' ]]; then
            sudo rm -rf /opt/ghc
            sudo rm -rf /usr/local/.ghcup
          fi
          if [[ ${{ inputs.remove-codeql }} == 'true' ]]; then
            sudo rm -rf /opt/hostedtoolcache/CodeQL
          fi
          if [[ ${{ inputs.remove-docker-images }} == 'true' ]]; then
            sudo docker image prune --all --force
          fi
          if [[ ${{ inputs.remove-aggressive }} == 'true' ]]; then
            # apt-get too slow, take 1~2min
            #sudo apt-get remove microsoft-edge-stable azure-cli google-cloud-cli google-chrome-stable powershell firefox 'temurin*' -y
            #sudo apt-get autoremove -y
            sudo rm -rf /opt/hostedtoolcache/
            sudo rm -rf /opt/microsoft/
            sudo rm -rf /opt/az/
            sudo rm -rf /usr/lib/google-cloud-sdk
            sudo rm -rf /usr/local/share/powershell
            sudo rm -rf /usr/local/julia*
            sudo rm -rf /usr/share/swift
            sudo rm -rf /usr/share/az*
            sudo rm -rf /usr/share/miniconda
            sudo rm -rf $HOME/.rustup
            sudo rm -rf /etc/skel/.rustup
          fi
          echo "... done"

          VG_NAME=buildvg

          # github runners have an active swap file in /mnt/swapfile, or somewhere else
          # we want to reuse the space that the swap file occupied, so we find all file based swap and clean them.
          echo "Unmounting and removing swap file."
          for f in $(sudo swapon --show=NAME,TYPE --noheadings|awk '$2 == "file"{print $1}');do
            echo "removing swap file $f ..."
            sudo swapoff $f && sudo rm -f $f
          done

          echo "Creating LVM Volume."
          echo "  Creating LVM PV on root fs."
          # create loop pv image on root fs
          ROOT_RESERVE_KB=$(expr ${{ inputs.root-reserve-mb }} \* 1024)
          ROOT_FREE_KB=$(df --block-size=1024 --output=avail / | tail -1)
          ROOT_LVM_SIZE_KB=$(expr $ROOT_FREE_KB - $ROOT_RESERVE_KB)
          ROOT_LVM_SIZE_BYTES=$(expr $ROOT_LVM_SIZE_KB \* 1024)
          sudo touch "${{ inputs.pv-loop-path }}" && sudo fallocate -z -l "${ROOT_LVM_SIZE_BYTES}" "${{ inputs.pv-loop-path }}"
          export ROOT_LOOP_DEV=$(sudo losetup --find --show "${{ inputs.pv-loop-path }}")
          [[ ${{ inputs.btrfs}} == 'true' ]] || sudo pvcreate -f "${ROOT_LOOP_DEV}"

          # create pv on temp disk
          if mountpoint -q /mnt;then
            echo "  Creating LVM PV on temp fs."
            TMP_RESERVE_KB=$(expr ${{ inputs.temp-reserve-mb }} \* 1024)
            TMP_FREE_KB=$(df --block-size=1024 --output=avail /mnt | tail -1)
            TMP_LVM_SIZE_KB=$(expr $TMP_FREE_KB - $TMP_RESERVE_KB)
            TMP_LVM_SIZE_BYTES=$(expr $TMP_LVM_SIZE_KB \* 1024)
            sudo touch "${{ inputs.tmp-pv-loop-path }}" && sudo fallocate -z -l "${TMP_LVM_SIZE_BYTES}" "${{ inputs.tmp-pv-loop-path }}"
            export TMP_LOOP_DEV=$(sudo losetup --find --show "${{ inputs.tmp-pv-loop-path }}")
            [[ ${{ inputs.btrfs}} == 'true' ]] || sudo pvcreate -f "${TMP_LOOP_DEV}"
          else
            echo "/mnt is not a mountpoint,skiping creating LVM PV on it"
            export TMP_LOOP_DEV=""
          fi
 
          echo "Recreating swap in zram"
          # create and activate zram swap
          # we need linux-modules-extra-azure for zram on GitHub Action
          # see https://lists.snapcraft.io/archives/kernel-team/2018-July/093622.html
          if uname -r |grep azure;then
            ZRAM_EXTRA_MODULES=linux-modules-extra-$(uname -r)
          fi
          sudo apt-get update -y && eval sudo apt-get install -y zram-tools $ZRAM_EXTRA_MODULES
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          sudo rm -rf /var/cache/apt/*
          sudo sed -Ee "/SIZE=/c \SIZE=${{ inputs.swap-size-mb }}" \
            -e "/PERCENT=/c \#PERCENT=100" \
            -e "/ALGO=/c \ALGO=lz4" \
            -i /etc/default/zramswap
          sudo systemctl restart zramswap.service

          if [[ ${{ inputs.btrfs}} == 'true' ]]; then
            eval sudo mkfs.btrfs -m single --force "${TMP_LOOP_DEV}" "${ROOT_LOOP_DEV}"
            sudo mount -t btrfs -o defaults,noatime,compress=zstd:3 "${ROOT_LOOP_DEV}" "${BUILD_MOUNT_PATH}"
          else
            # create volume group from these pvs
            eval sudo vgcreate "${VG_NAME}" "${TMP_LOOP_DEV}" "${ROOT_LOOP_DEV}"

            echo "Creating build volume"
            # create and mount build volume
            sudo lvcreate -l 100%FREE -n buildlv "${VG_NAME}"
            if [[ ${{ inputs.overprovision-lvm }} == 'true' ]]; then
              sudo mkfs.ext4 -m0 "/dev/mapper/${VG_NAME}-buildlv"
            else
              sudo mkfs.ext4 -Enodiscard -m0 "/dev/mapper/${VG_NAME}-buildlv"
            fi
            sudo mount "/dev/mapper/${VG_NAME}-buildlv" "${BUILD_MOUNT_PATH}"
          fi

          sudo chown -R "${{ inputs.build-mount-path-ownership }}" "${BUILD_MOUNT_PATH}"

          # if build mount path is a parent of $GITHUB_WORKSPACE, and has been deleted, recreate it
          if [[ ! -d "${GITHUB_WORKSPACE}" ]]; then
            sudo mkdir -p "${GITHUB_WORKSPACE}"
            sudo chown -R "${WORKSPACE_OWNER}" "${GITHUB_WORKSPACE}"
          fi

          FREE_SPACE_GB=$(( $( findmnt --first-only --noheadings --output AVAIL --bytes --target "${BUILD_MOUNT_PATH}" )>>30 ))
          if [[ $FREE_SPACE_GB -lt ${{ inputs.min-space-gb }} ]]; then
            echo "inputs.min-space-gb: ${{ inputs.min-space-gb }}"
            echo "$FREE_SPACE_GB GB free space not enough, action failed!"
            exit 1
          fi

    - name: Disk space report after modification
      shell: bash
      run: |
        echo "Memory and swap:"
        sudo free -h
        echo
        sudo swapon --show
        echo

        echo "Available storage:"
        sudo df -h
